version: "3.9"

services:
  node:
    build:
      context: .
    container_name: "potential_crud_dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/app  
    depends_on:
      - db
  db:
    image: "postgres:12"
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=developers
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
