version: "3.9"

services:
  node:
    build:
      context: ./src
    container_name: "potential_crud_dev"
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/app  
    depends_on:
      - pgsql
  pgsql:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=developers
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
